#!/usr/bin/env python3
# vim: expandtab smarttab ts=4

import sys

from common.configs import *
from common.logger import GlobalFileLogger
from common import argparser

from tui.WindowHandler import WindowHandler

def para_run(cmds, gfl, args):
    window_handler = WindowHandler(cmds, gfl, args)
    WindowHandler.start_main(window_handler, cmds)

def main():
    args, cmds = argparser.parse_cmds()
    gfl = GlobalFileLogger(args.debug_level)

    gfl.log('MAIN', 'para-run (v%s) launch!' % VERSION)
    para_run(cmds, gfl, args)
    gfl.log('MAIN', 'para-run shutdown successfully.')

    return 0

if __name__ == '__main__':
    sys.exit(main())
