#!/usr/bin/env python3
# vim: expandtab smarttab ts=4

import sys

from common.configs import *
from common.logger import FileLogger
from common import argparser
from common import runner

def main():
    args, cmds = argparser.parse_cmds()
    gfl = FileLogger(args.debug_level)

    gfl.log('MAIN', 'para-run (v%s) launch!' % VERSION)

    runner.para_run(cmds, gfl, args)

    gfl.log('MAIN', 'para-run shutdown successfully.')

    return 0

if __name__ == '__main__':
    sys.exit(main())
